services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8082:8082"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1234
      - DOCKER_INFLUXDB_INIT_ORG=myhouse
      - DOCKER_INFLUXDB_INIT_BUCKET=energy
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token-123

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  emeter-logger:
    build: .
    network_mode: "host"
    depends_on:
      - influxdb
    environment:
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-token-123
      - INFLUX_ORG=myhouse
      - INFLUX_BUCKET=energy
      - INFLUX_DATABASE=energy

volumes:
  influxdb_data:
