{
 "title": "More Power!",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurementTagValues(bucket: \"energy\", tag: \"alias\", measurement: \"emeter\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Household Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VoltageMV\")\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> group() \n\ndata |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> map(fn: (r) => ({ _time: r._time, Average: r._value })) |> yield(name: \"avg\")\ndata |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)  |> map(fn: (r) => ({ _time: r._time, Min: r._value }))     |> yield(name: \"min\")\ndata |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> map(fn: (r) => ({ _time: r._time, Max: r._value }))     |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Unaccounted for Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "data = from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"emeter\" and r._field == \"PowerMW\")\n|> map(fn: (r) => ({ \n      r with \n      type: if r.alias =~ /.*total-consumption.*/ then \"total\" \n            else if r.alias =~ /.*production.*/ then \"exclude\"\n            else \"plug\",\n      unique_id: r.alias + \" (\" + r.device + \")\"\n    }))\n  |> filter(fn: (r) => r.type != \"exclude\")  |> group(columns: [\"type\", \"unique_id\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> group(columns: [\"_time\", \"type\"])\n  |> sum()\n  |> group(columns: [\"type\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"type\"], valueColumn: \"_value\")\n\ndata\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: \"Unaccounted Watts\",\n      _value: (float(v: if exists r.total then r.total else 0.0) - float(v: if exists r.plug then r.plug else 0.0)) / 1000.0\n    }))"
    }
   ]
  },
  {
   "title": "Watt of Power",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerMW\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> yield(name: \"watts\")"
    }
   ]
  },
  {
   "title": "Chaos Voltage View",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VoltageMV\")\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> map(fn: (r) => ({ r with _field: r.alias }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"per_device_avg\")"
    }
   ]
  }
 ]
}