apiVersion: 1
datasources:
  - name: InfluxDB_Energy
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      organization: myhouse
      defaultBucket: energy
      version: Flux
    secureJsonData:
      token: my-super-secret-token-123
