services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    network_mode: host
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1234
      - DOCKER_INFLUXDB_INIT_ORG=myhouse
      - DOCKER_INFLUXDB_INIT_BUCKET=energy
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token-123

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1234

  emeter-logger:
    build:
      context: ../../.
      dockerfile: cmd/emeterlog/Dockerfile
    network_mode: host
    environment:
      - INFLUX_HOST=http://localhost:8086
      - INFLUX_URL=http://localhost:8086
      - INFLUX_TOKEN=my-super-secret-token-123
      - INFLUX_ORG=myhouse
      - INFLUX_BUCKET=energy
      - INFLUX_DATABASE=energy
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
